# Generated by Django 4.2 on 2023-05-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('house', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField(max_length=6)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.IntegerField(max_length=10)),
                ('date', models.IntegerField(max_length=10)),
                ('note', models.CharField(max_length=10)),
                ('billamount', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=30)),
                ('pin', models.IntegerField(max_length=6)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=30)),
                ('pin', models.IntegerField(max_length=6)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine', models.CharField(max_length=40)),
                ('cost_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(max_length=10)),
                ('quantity_in_stock', models.IntegerField(max_length=10)),
                ('maker', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=20)),
                ('medicineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.medicines', verbose_name='Medicine_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdate', models.IntegerField(max_length=30)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.animaltreatment', verbose_name='Treatment_ID')),
            ],
        ),
        migrations.AddField(
            model_name='animaltreatment',
            name='Medicineid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.medicines', verbose_name='Medicine_ID'),
        ),
        migrations.AddField(
            model_name='animaltreatment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.doctors', verbose_name='Doctor_ID'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100)),
                ('insurence_id', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('name_if_any', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
                ('note', models.CharField(max_length=100)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.animalowner', verbose_name='Owner_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(max_length=30)),
                ('discharge_date', models.IntegerField(max_length=30)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhmsapp.animal', verbose_name='Animal_ID')),
            ],
        ),
    ]
